@startuml

abstract Control{

    +Plants[]
    +Inputs[]
    +Gains[]
    +Errors[]
    +Jovani[]
    +State
    +Feedback() 
    +Timer()
    +Controller()
    +Felipe()   
    +Jose()
    
}




@enduml